apiVersion: ENC[AES256_GCM,data:lxU=,iv:KtNdWg9gBuymLx3oTs8L35m6RJfDD5sK0NYEt8Zukyw=,tag:FQ574UXlsuvR4RL94y7uGA==,type:str]
kind: ENC[AES256_GCM,data:QSgAWX11,iv:n4VM7PJsuYSEL3LYEC7UyLPi+rvIbbWFqMm7/pouvkQ=,tag:0v0k+2wvcIiqZEHBYiiELw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tCTxyaVuG/WL9LOCPA/RpOnflkg=,iv:QKsG8qgYZw88axHpj8ztnQF0qWj7rFIJ7zmJagAEm3Q=,tag:PBlDQ8xXLbO+L0vG3myXLw==,type:str]
    namespace: ENC[AES256_GCM,data:kKcntFU=,iv:Htt2HGA0Tu3EHaIlfj5RII9OdfRxlmrFoutqNpluAKs=,tag:0oFwz02lDGHN7Nlb13/C+Q==,type:str]
type: ENC[AES256_GCM,data:Kmv0RhkP,iv:Vk2G4OCNMiVXoCr7Uw6Jr5lQNy6Q8WW6DTCKQfR4Djk=,tag:tR0ufSUFfDTihPmCKLyWjg==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:VR49IRDfcJBROzuog12hZX5YoE0EMqdvSgkZ0d7NlfaPd+CNIfA1wEb9vF+GAU4P,iv:CvhzRcDfm99Dy4ti77vNUwpQP098CFNOfGDNBnxIyys=,tag:kSHEyHGP20M679WDcOrBTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEhMc3J5USBBKzdsbXg2
            cG5veUxwMzhaeFJjV0VCaS95STBtcHZCYUVuOG5mUjZ3WjVPSApmOW9NelkvUzAv
            MEM3eStmN3dBV21nbkN0WjJWQmVNd1NOUDk1UlJCclRNCi0tLSBWbVB4ODdidjhY
            ejg2TE8vSTVIemZzK3l1YkdjNVNBL2ErOGdBdS9GTXVnCmSNaAiwOfsBOIm1Gnkz
            +bDkhWWlZ6mAWIvgiRRUrHDHc/Hw7/6T7gjOZPgxAk5rwXYLxiZbKIrRdWvzjodN
            jjw=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qfn5svgndezuxfseqmq0f68sw8qex7scxrkgzjdjdm86hm6nxfmj5d8a97h
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNejlNeEt2NzhtbzRaUXZu
            WVR1NE5oWms1WGEvS2hwZHZaaW9EK1RvSURFClJWNHRQN3lwcHBZbmF6VE44ZHJ2
            ck9sakl5anh4ZnpLYUNrVWxQaURwTWcKLS0tIEdiS1lPKzFmS3IwWGp5dldZbDVr
            OWFPNzgrWXY5OUk5cFBZZmZNR1Z1TlEK3XwOq64eBbrE3EnWCJEA01vXj/PvOOAF
            +vMcVTaBR+j6RsFQTwKQxHopJHA3+1MX5XhlGO6R/QAAwLtSbZ++EQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t92fpnhk4s9apje356hfsadsh2c8prspmy6jshqfwn3dxyzr73sqpp4ac3
    lastmodified: "2026-08-20T15:39:01Z"
    mac: ENC[AES256_GCM,data:7RJpKKYameC/QIaSO7azdRv3Zjsx3nYQJNh6ya+/TO2uhug4Yw3sUJDpgYshHVTSuxIhbblwv8F6ewuDglaAMqVFQ9QqAZsdpZLigxBwbMSsxqa2HyffHX51T5CL7YygdqaZDr1pRsx/loz/bc20iBgncYRXdP7nhyA+YC7eHMg=,iv:2wbUiNxfq3ndQI30wXcuhbSEQW4EseZJUBJGyfv7Uls=,tag:N8GB+6NJcI+1Gf0RMZYQcg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
