apiVersion: ENC[AES256_GCM,data:ldk=,iv:1qYG7fdJGKxkS9HQrMcPlDy/SN2gJ+6INULIMXqsr/4=,tag:cAxcImp8B+V7Gfnfqw2ltg==,type:str]
kind: ENC[AES256_GCM,data:vKtaFRjt,iv:YDWaob0j1bW18A2d9kXaNW5tKNZXaXGYmXjtiimjAY0=,tag:nGtZM0KrArHCpgGBWvdS9Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZwrUKlpNzvjm2Xd+uFf2qPfLvvo=,iv:SKyUdyHnta247ZGHZXA5cU9Tj5D8Ayd5WitradNTN+o=,tag:JDj6pEdQFiWHpQ3EO2JtZg==,type:str]
    namespace: ENC[AES256_GCM,data:fbYyc+Q=,iv:rWXg6d2jnAuETZrHcA6gUXc9m4fiRr/XiZyscG3Ce3Q=,tag:g+d5Ystqf69ji7PN8dM3Iw==,type:str]
type: ENC[AES256_GCM,data:sNppiO+4,iv:iUN0IElOvT5IPAErJPlLOUQ/HbHcliivs4CNfPQcFmo=,tag:Ns4JR/AZvJrW1ctuVTzwXA==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:aEhBOWTTMDv9oKI1kA==,iv:/NrbTZU7DyOW3unVY1yBLHnL5risOrDDJmJ37KDhsO8=,tag:Y+1YF5uA0cTM7NrhNLLdQA==,type:str]
sops:
    age:
        - recipient: age1vlvyzq58d3t94ttecf92pphhr7wx75353mvafeqdlhurda52f5lsu0dwlm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSmRJRkpkMUd6UGF0Ym9U
            T3YvZGpqQ3dUd2pxaDg5b0xiVUorb0NiYkQ0CnRZYXJWVC94QWxkRGFkcXQyOERk
            VEx4bFFhSXE1N0NreTFGL1R1Um9aekkKLS0tIGtFS0gzZjlBVUU4Y0hadGhDVVcx
            aXF4RWxUbWlESHNnZG83TSsreXJjc1UKZUIL9HWtBY9tTVRMBvUJeLWJGT9hZYYS
            leTMVP8pB7kotumN7vQS/Gw14UO1Z3JDxet30OGljPBGV1wk0he8SQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T15:24:52Z"
    mac: ENC[AES256_GCM,data:tAptS9kmHy7QLuCOFLNq5O4+ygdM4aOnrTvqAyvZdK7NehNFfbSOXvpw+NCal+rtEmX3nQt7AsRTT+I3k/ScHQ3mZ7CSvoq+sB5gUnwwdeM9T2l0HnGF4UUspS6D2VTBLVQd2o2ne7DHqEJfIpeep7GXs5+DVsPvqa1I5bhYcdA=,iv:mrb1DQRLxUbXnJ7dazGBlGIjq3cwf6cQvmSb1nk4D58=,tag:JSERL4XyO64F0/0mC//1Nw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
