apiVersion: ENC[AES256_GCM,data:vmU=,iv:eo2hS3rhHMLKmgmz80RBO/OScUKYRnoxeZktEVMNeu0=,tag:ClQVx0ihClhXXC+0vqCWEw==,type:str]
kind: ENC[AES256_GCM,data:Tv7DYER/,iv:+uohaE6ltzbL+JUs2oqR9/Ojc2PSsCRT+9WQkJ4xRj0=,tag:aEvSrh0rqhZZgFWMFQ2oXQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:X9QB4sffWfxGULeM7OXzOZj3yGI=,iv:R6n3V79FiRRPwsC+nwciTeJ0qibSjb1+M7ylz/YBCSM=,tag:Dk+ZeBtkFn8hvEpnfiS6vA==,type:str]
    namespace: ENC[AES256_GCM,data:uUFVrs0=,iv:eh4hOxdtSy2pp4KfnFajz0x7OdY3OEEQ4hCtJpQJp08=,tag:7eJQ3jOH3q4Xf+gqektYXg==,type:str]
type: ENC[AES256_GCM,data:ZaxA/TUg,iv:leyj9YJ8XauKmAIygeKhPqCACnX0dKcc1wSUjX1sWKc=,tag:pcQca45bwVCkmFcQJ/8GGg==,type:str]
stringData:
    postgres-password: ENC[AES256_GCM,data:R8lQEeOjNIoBjbrOuy0=,iv:TuK13f1DdEvrwSsrjF2aSjOrBI7VDz5u0uYfHUYFtVk=,tag:nCH+wchvE2zWNGMkGGM/VA==,type:str]
sops:
    age:
        - recipient: age1vlvyzq58d3t94ttecf92pphhr7wx75353mvafeqdlhurda52f5lsu0dwlm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRy9FRmhlMFk4LzZGSWlZ
            OHIyRmJxNEp5c29IdjRWbmhTbGNFaWdPaUJVCjUvUWpJbko0N1lyVVEyRHNIZzVa
            ZVNhaHFZUTcrdXNjYUV6U1JxYUYzdEUKLS0tIFZlNElvZ00vZHVRc2htRWFKcnZL
            U3lkZ0c3NkhVcEJQVG9TNEt3UkF6VHMK8mvCtgRvdKSWmx/oBEBwOGGoxkYXecbC
            OlDYIWJACsbhNHZLEloTNg9Kq/+JLsI2JW3YWjox49jq/8z+3PUlwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T15:15:56Z"
    mac: ENC[AES256_GCM,data:/MgWtaytE2xqeLpFt4/XG+x8LK1dwh/BifGhpKYvdjAWRhvWPJiVSibr6RpGnryJaNdQ/k7jMo2SH3EJV+HW1k9VAbzHvOF7TslSSeHIcKUjiWII67Ay2UGkK2EqFxOVSwxOqchw/neV7+2Q2oURW9AnWXKzWGGoEmqx5jrx8X4=,iv:nsUvdOGDSHh2JyX9zSRqAd1BNtpL/tr7ZiT5QO+RKio=,tag:hhrMYJCRmjX5KNypd9qO5Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
