apiVersion: ENC[AES256_GCM,data:iQ4=,iv:6IIl135x+a9mF6Ym/+Au5XjblrezPECQs+Il26t6OfQ=,tag:s/jvQyHZzKLKFM9O9TMDfQ==,type:str]
kind: ENC[AES256_GCM,data:VTHvvv5G,iv:3dyzL1ozW4kibfGGH981tPREbTxKkZzTEMuDsPrMX8I=,tag:fLsRDzFehGUIOvAAYKBLtQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zeFyTkZZmbTZV3QAPBW1Xf6t1x0=,iv:YUnq8ucKzZn8j7OUTm4XX6R8cPhhG9oj9S6x/iCdVj4=,tag:fWvWBRhfm7d2Q9fl1A+sEQ==,type:str]
    namespace: ENC[AES256_GCM,data:PTYjIXk=,iv:5sx0p5D1wtajRzcbyUmoS0yKfr5Un8/AFp4PZOLn2/w=,tag:15PnvXV/tv2hEHN0SwUSRQ==,type:str]
type: ENC[AES256_GCM,data:DU88vHC+,iv:2wiKf626O3NPn2g78Y0Ec9av0xldQxWXtdtcwu5NKRA=,tag:FUhNwJIhurGbGtb6/1SfPw==,type:str]
stringData:
    postgres-password: ENC[AES256_GCM,data:PgqyNbToskoTgx2r7KCkok9OMBLiLoHPjQHsRJ8RG4dy9taII+BWNpRuznNP5rh7,iv:1hoWhkswBM+P/nIXWYEv4tFfgW4RRQ33Gn39uJ0sZRY=,tag:yfboMoPor4UgphR1usJwzQ==,type:str]
    keycloak-db-password: ENC[AES256_GCM,data:XYxEso8lZY66VhsxUver1hGSo1jlutyxIsaN+TfcosEUI8D0GzgYFCSJXQkzhZ0H,iv:H8TiR6qkaJXoWCP/86ffPLRIfyK9/sn11cVUgl/zciA=,tag:eb/GFXS+Mfdkh2YWirzH1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEhMc3J5USBBemxJZkdh
            aGZwQ2k1L3V1WVZNS0VJOHlwa3hzK1RRaFNqRjVBTnVHOHk3YQpTRk1rMEE2S2Y2
            b1RTanhDL2F5SjM2cjZhRVRyQVpUMFZtM201MzM2WkJBCi0tLSBUMng5VDdSWS8w
            eGd2a0JRN2wyb1ZCUTNxeVZMMTFmNDB2WXhGK3JqdWNjCqr0FsrpB3WnRveL0+m9
            ZOWqC9WuR33RrhoeSY6X1/22E+6WYGR3c0KkfLvYYpv/TXkHmqLiRr0muilz8OK9
            uWs=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qfn5svgndezuxfseqmq0f68sw8qex7scxrkgzjdjdm86hm6nxfmj5d8a97h
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aS9KRzRVM3R0QVNjMGJ6
            VUpLQ3NuMnFSZFdtc2RBRytBamdFSWtVVVZzCmhObXNheDZGZjl6MFBZOEJWYlVz
            WGd2NGJ3QlJidXYvVjAxOGVvcVg0SVUKLS0tIGJXczhhZ2c1VjNoZUJnWXI2MUVW
            WVdmaFVYbVRpTWhqMGZKeXBpMzQwUkkKaWMp76pPJ62FvTWJxHqL8rdx66saPla5
            f8DLmQIliIGokXX30n9tXDEQQ+gZPs+VrFSGwK7SniNaoqMoLjDI/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t92fpnhk4s9apje356hfsadsh2c8prspmy6jshqfwn3dxyzr73sqpp4ac3
    lastmodified: "2026-08-20T15:39:01Z"
    mac: ENC[AES256_GCM,data:M5edN9pGF7wu7dW5phA0Vm7ElzQhzTy2OfxZcx8Own4sl5DTatBwG8VngW6CmMagHG3H4Mi8ldxOw21tYdHo/PQSBfaUBfFk7DKH9JxS0sQcp6XKZksmzIaL1HW8wGdLUDihVgWjgNMXt5JlcFKFfMUsAHWMw453Eh052uqwnsg=,iv:Ktq4tv7g+heuJnhBG6bq3wmON/7YSRe9PnUI0G21NHs=,tag:Y+NGe6T5HZAWJeugpOlV9A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
