apiVersion: ENC[AES256_GCM,data:vmU=,iv:eo2hS3rhHMLKmgmz80RBO/OScUKYRnoxeZktEVMNeu0=,tag:ClQVx0ihClhXXC+0vqCWEw==,type:str]
kind: ENC[AES256_GCM,data:Tv7DYER/,iv:+uohaE6ltzbL+JUs2oqR9/Ojc2PSsCRT+9WQkJ4xRj0=,tag:aEvSrh0rqhZZgFWMFQ2oXQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:X9QB4sffWfxGULeM7OXzOZj3yGI=,iv:R6n3V79FiRRPwsC+nwciTeJ0qibSjb1+M7ylz/YBCSM=,tag:Dk+ZeBtkFn8hvEpnfiS6vA==,type:str]
    namespace: ENC[AES256_GCM,data:uUFVrs0=,iv:eh4hOxdtSy2pp4KfnFajz0x7OdY3OEEQ4hCtJpQJp08=,tag:7eJQ3jOH3q4Xf+gqektYXg==,type:str]
type: ENC[AES256_GCM,data:ZaxA/TUg,iv:leyj9YJ8XauKmAIygeKhPqCACnX0dKcc1wSUjX1sWKc=,tag:pcQca45bwVCkmFcQJ/8GGg==,type:str]
stringData:
    postgres-password: ENC[AES256_GCM,data:R8lQEeOjNIoBjbrOuy0=,iv:TuK13f1DdEvrwSsrjF2aSjOrBI7VDz5u0uYfHUYFtVk=,tag:nCH+wchvE2zWNGMkGGM/VA==,type:str]
    keycloak-db-password: ENC[AES256_GCM,data:VmbjA08kpiYV0NPgrl0V8x8=,iv:TJYKTk3ljjPRyzR0flyT12zhkoremH0IIHhOnI/0uco=,tag:EDFYXlU8tdI3cD7DEqU9KA==,type:str]
sops:
    age:
        - recipient: age1vlvyzq58d3t94ttecf92pphhr7wx75353mvafeqdlhurda52f5lsu0dwlm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRy9FRmhlMFk4LzZGSWlZ
            OHIyRmJxNEp5c29IdjRWbmhTbGNFaWdPaUJVCjUvUWpJbko0N1lyVVEyRHNIZzVa
            ZVNhaHFZUTcrdXNjYUV6U1JxYUYzdEUKLS0tIFZlNElvZ00vZHVRc2htRWFKcnZL
            U3lkZ0c3NkhVcEJQVG9TNEt3UkF6VHMK8mvCtgRvdKSWmx/oBEBwOGGoxkYXecbC
            OlDYIWJACsbhNHZLEloTNg9Kq/+JLsI2JW3YWjox49jq/8z+3PUlwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T16:44:32Z"
    mac: ENC[AES256_GCM,data:+6vpYpGPY9xplJWBfavi5l0HLYBcOErJuaHId0h/hF+DoERQVw7qwQTqu1o6vLfuI00KVV1pgdRAfo4lN42BtK3zZo4QIDhlJGr99dh+V9BWx88z5aatpwlhA5mKyYRkvWUBSFfFG3o8Dr7OYAUEMpfkHk/gv3djaJleb2FuCDI=,iv:FGCkcZ9KIIOhLyLOwdMMJwXx2IM5PP2MYlk+rnv4eWc=,tag:EySKBSToDpzlmRrHYYzLNw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
