apiVersion: ENC[AES256_GCM,data:vGA=,iv:zOQIMOJ/1Ttg1DCJf2fZgSLujayoz83v/ErcCY/aGf0=,tag:T2Dy05bM+jkIKmTMpXQwRw==,type:str]
kind: ENC[AES256_GCM,data:RO0lc/8p,iv:/0jKYTF6rhfKfz2OiwisVVXhzFBUj2qHBHXx6fnHv3M=,tag:mPZKelZ6nN3kqegY+p7KAQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XOYBZSrcIXlBAwkQY9SG6/whNA==,iv:3SsMWtrZifsqYeRwDICFL8mVGQaKTDiShG+dXe+zbCE=,tag:4T+SMT6ac/JQE6dSxNfRqg==,type:str]
    namespace: ENC[AES256_GCM,data:pTpuoUk=,iv:l9w4u3FNn3m+zSrPrp/gZOqRVVkSIGj/mtEPCczCkGA=,tag:nrgtWgnBxDLZb/UgpVKCVQ==,type:str]
stringData:
    preshared-key: ENC[AES256_GCM,data:qPVw8FWgXQVxspDjAtEGQaBY3Jv0k4wesTmcxu8SBkKhiDVfkskx3DdiFYEnDkJ3LWW7UXr0clWDh+9goOzjMA==,iv:EyZbFurSzowAX+OJz4MwGitFvENvEGWCiYTJvU3EVtM=,tag:8z9OR0LwpcKwk9rk/GjONA==,type:str]
    db-password: ENC[AES256_GCM,data:Ei6Eko2yqj+V1mLDE1L/IOeJ+SeSucbLMZaoIrb5yS3ecvlspSZTxJyNxHP4CEg0K4lUSG86UEZ4n0DngSbGMw==,iv:cYd2Pjy8+Z85qEX8TXJn2OoZu98QDZOodnThDfKObEQ=,tag:qptHJmd5+EYeKXU+ATj20A==,type:str]
    datastore-uri: ENC[AES256_GCM,data:tzvidsbh5H0Gv2ayoUIzY0claH/S5Z10jQjTpO7j9poa85eKmbcJZDEAxrSzz12IDeuYSVn1/Ub4gYw9H5EIZVEnpIpwe5iA9QSI1RhnG/Afxemn5yROmbYYsHDsvjfjfyzwB4kY9fuycitCyMxAQSmD0uyScJz/qP1quFEjSce0lv8O2TmRHcGe,iv:r4hw3oFs1FrZFU26ZcM3u8Q7dFft1ZXWTjtNYhmrKkY=,tag:WW/gIKqvU70JX75BkFzayA==,type:str]
sops:
    age:
        - recipient: age1vlvyzq58d3t94ttecf92pphhr7wx75353mvafeqdlhurda52f5lsu0dwlm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNzRObklJcllLbEVIeTdM
            SGF2NERadVhzYlJmZ0o2dk43a1QxUk5QREVrCnpRaEl0Si8xZkFVN016R0xqN1Iw
            VUpmM1pnQnlQT09mOFpzQ0hhV3ZwYmcKLS0tIDRUeFF6VkFhVUtsellXa29JM0NO
            Sm1WQzlqSUpYZUpNVXFuTVFkczJ2ME0K9Qn3abmwx/CN1O1Jm9CBvRXX4k6vDmLZ
            2LkEVi4Ag1C5DU7lCVdgykwENtPgjQRWjw0VLoBRwPnVpcGQ5XKu/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T16:30:13Z"
    mac: ENC[AES256_GCM,data:0sVaHz6TMoVwU+A7ppdCb+gKRXIZomaZG4k9fdZuNPtJux8dYMGCQN19VCQ73CE71nDOv7LfFQag/MQPFFqSQHJIaZCdz6dnzeaVE6xGz8s+KR3/9taKOJj1ldVJm3tj1NE3caGEhB0WzMgrgfqzt5cJzXM0bSy/6QloT8Cvc3g=,iv:NnfGWvpGyBCtG5vIwu/V6ljsZNkvvcMy/5Au7GYajC4=,tag:oLlMogHUzenMaw65ILd1mg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
