apiVersion: ENC[AES256_GCM,data:2uk=,iv:zqEOr/gEmcNm28YkjLJTUtNp699YAlnu4uzC+wblPYg=,tag:pWGRaCQw2OVT4ujzgq8/OA==,type:str]
kind: ENC[AES256_GCM,data:dkfR/A0N,iv:WrIFh8nU5DsSHV7E/X9pzcLCreosSKj4jBWoV2CKNrs=,tag:PP4zrnvJwUCoBFV7GVBipw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/Q4RSsN9qUcysNKVULulXoEamw==,iv:yC75GYy697ukVB2fajRn7uWleN3NCZ8BCw+Dj+0il2A=,tag:j1LxbroC+d+YZheymFUcQw==,type:str]
    namespace: ENC[AES256_GCM,data:kxUd/sg=,iv:VfFqBSac5W53sdoEQMJP3aIVzxxU4zqQk1WulUBAThI=,tag:lru31kUzzI+5ecPweD5s1A==,type:str]
type: ENC[AES256_GCM,data:GKzJ7jfr,iv:TeUXEV5ZMRI94A33jzl7P7Mcejuu0jKtSjIFiyOs1vc=,tag:TSOdoNWv406YisqxNzkRaQ==,type:str]
stringData:
    preshared-key: ENC[AES256_GCM,data:uGtg3iZXffnXn1TBAjijq1ykrCPhO7X21emBwYJ3MUdVLJVag0lgkjCXs6DJEpX/C0X3iFUU7x11W+a4RJ4u1A==,iv:vQBd45h1aE1VxA+xPNzajsIcGNIYtAFJ5q2FVf4f/To=,tag:Su+trSBTAV+VS+iALjbCSQ==,type:str]
    db-password: ENC[AES256_GCM,data:No1D8R4i+pTIoDMOkl9tR8h8sxP3ffC5CHeYluWpy+2hbia9O7i6tSIbdMvkbOxO,iv:bg9tZmBm8zUZA4IXHhhl06LXv69nFA7Jl0CWs8dfZiA=,tag:XiOwyLzKRio5UQBQli2L2g==,type:str]
    datastore-uri: ENC[AES256_GCM,data:mFCoLT9jWZ00MZiCLmfD9l3GBJGoM2FAPalzFyej/yJzw8SyLz1nTbDjBcJQDoQWPibuCUjQkKqyPJmqrzWbsU8bkyl6ARQzASdhqFkEaXpayoSHNuzSoiCFLrGEjJT4SWJBB5hFbOxedOD2N7NEVCuyxf5SrfKXMPfSrdaECewULNY=,iv:D7D4oDWOg26K3pFIdBEwkPge1h/MyivkZYS0+5sojSI=,tag:KBFnEKalx6wQBSe2n9coXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEhMc3J5USBBeVN4UWEx
            OWkzMmwxOWgxRlRuZlpmNUVVRGxMMTROeVpIRzA1MUFHMFlBbwpTSzhLSGpvZk1K
            N1h0cDBlRG5ZM0FjTE9aLzY2clh5UnNNRkhNOUEyQ2ZBCi0tLSBUeWNoZkdVaFQr
            OUswYjduOVkrU3l5MVFteGZobkFNWm13bE9CZllyanEwCg+1sLb02S7ttu4QH3nQ
            TEuV36fFalgJTEFbcUlHxUVHmTYEL/oaMpg81jiKfQtCRlkd/JUgSl8LDo348RNt
            HFQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qfn5svgndezuxfseqmq0f68sw8qex7scxrkgzjdjdm86hm6nxfmj5d8a97h
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcHovdkZWcEV2TWE3YlE3
            Y3J6ZUdyRXRmM29KeEU3L053RTNUeStnOGgwCkgyYXB4bzdUbGdwQ3BRWTh5b3Yy
            cCtGUjVVVG1MSVg2UzRiZFNWNm12c1kKLS0tIFgyeWIxZ2UrYmNORStMU1dHZjJV
            M0M0UjBQcllCWG5EdEpoY0h5UVVldmMK3gosTMDKUSJT9UQbuwTAzBkzNqssGlyf
            fAxETk7sz9lIHXeT4SRkElkLico46vShqMEnX6fUP6r80yf1Gf2Saw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t92fpnhk4s9apje356hfsadsh2c8prspmy6jshqfwn3dxyzr73sqpp4ac3
    lastmodified: "2026-08-20T15:39:01Z"
    mac: ENC[AES256_GCM,data:7lWA6wXWXPbH3CE82fDZPkuFTKE2KHHHQFr4h3CLZ0NCbzd268nAf4N1SE4cy6YJl0nGmgI56MuQbP39YwVd/7eGfaB1KRPPyT6nNa5dOfQuGdbV3FRe4B40kKV5hQya7OoDkxDvpAETQSW4z9CcLnXoAVuSwvo0YQ+eF3swL/4=,iv:UBsKQhlLuCF6sMJBssxj7FWnpfhLhUv5ffljr2/OBKE=,tag:CVWIUQRzXrRPSY60tJ0Yfg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
