apiVersion: ENC[AES256_GCM,data:f7E=,iv:z6ZmlPT5ldL/aao2ydzepcrMx8JRqIfJpiOoqi6mvA8=,tag:Qj+0HNH2t3HvBNljTCNzyQ==,type:str]
kind: ENC[AES256_GCM,data:eWQG3S97,iv:Z7EcwuhCX62T43QRYy8NjQfAJ1g/FWfy3eyRqcuWh7U=,tag:lhR72ok35vgt1qO64vRn7A==,type:str]
metadata:
    #ENC[AES256_GCM,data:WfjSosftdl9Mg2sZ11bKT9Z0Tmb0sokpN2HQGwV7aJc3oN45ux6dtp/GFVAdoq4=,iv:jairplJ4+BwWL6rPVHAj/GuEBl0Ue2Y3eanq9wRsNo4=,tag:PNaEF91BLsqBlgg1E0Q/HA==,type:comment]
    name: ENC[AES256_GCM,data:41CAtUkCDwHUEHD3uhdUSf5BNTCUgS4xVj9+DaIz,iv:+ev+tcJV1m6QmgQgBftF43LJprgOgHLn+kDJ98QvVdM=,tag:lp0gEOsUzPnQjy2+/xD7xw==,type:str]
    namespace: ENC[AES256_GCM,data:6HyOuIE29hc=,iv:uUShiaYgSgJYOTU0vyOrx3Oo6s+qChsWLBz7RQY5PQ8=,tag:6q3BxfCRoz/9yrYAVn8urQ==,type:str]
stringData:
    spicedb-preshared-key: ENC[AES256_GCM,data:OD9IGtEaplf7h7KIFCUBYKeRoXXVgfLr/5GTHat5FmQAc02vxP1Zvbh6m9zFlLrRqiWlFym2Zouv46144BAdaQ==,iv:G5WZVG182ipulhJ3NTh1JLuzLuBTD0iZodk8uGOcTug=,tag:xGdf2GYrhA9CWd4Yr8Bosg==,type:str]
sops:
    age:
        - recipient: age1vlvyzq58d3t94ttecf92pphhr7wx75353mvafeqdlhurda52f5lsu0dwlm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZUZJUllaMzNYK0EvUUxr
            ZTV4Q3U2cVlrbzZyS0pGY3Eyb2NQa3RtTVV3ClUyRDAyZmkvcWc0cVkxQlJQR1RX
            dkpSMXVqSkV0cC9HcGt0L1kzamlSOEkKLS0tIC9DSnFsWHh6Uk5yOE56SDhyTm1Q
            NXl1WDBDSGJEWSswNjc4Q0J4VnFoSFkKA/TsSzwSI74w6e1WcfRjzzUqeX5MJGM1
            ftdSZ+Zvg18e00j3Yanud/gI40jvkeCS4j2GdPHxy1XFXBFn/uogeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-10T09:14:38Z"
    mac: ENC[AES256_GCM,data:LPyKfILvyNu+dGV9LUwjdwmtRgLddJZ7xHuQxTWDchoiOStE11App+7IaygCleDeLPPqnBCSwe75zTNYafhFEUq1atijlxD6NS7jgO5aKfUAHEVEMUf8ZF/9lkrzugAEYQprC9lUXCNL+QG/L/L03QcXYV7VCEMlnG8sWPVq6x4=,iv:9ACasvr51opYMsb/H7rmJkNMalyLGZIkbV0Yp/az0Mo=,tag:Ch1O4HU2PWtw48OHpb5/iw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
