apiVersion: ENC[AES256_GCM,data:mxo=,iv:xGgyWTz90gxoUgSjc/VuUq/qj9kCP/8UWrQhhtSOU0M=,tag:eP+VbyG2t7uab2Nz3MuhQw==,type:str]
kind: ENC[AES256_GCM,data:B4GFv1/x,iv:mkC6eBE/Nv0S311XXsyu65qGajQ0GOj/HRT6fIsc4C0=,tag:/wfcOQhgVXPFrrym4h0aSg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UGlQvIL0wdE6FGsc56l6Quw1lecXLmGNwoxWWRVe,iv:0uuT6e0rkUmQv8YlNwlsqzunMHkMIIw38DbcfJ2br7c=,tag:tsMPwUUsZEwGjYn8AO2bvQ==,type:str]
    namespace: ENC[AES256_GCM,data:kziYBTT4gbs=,iv:7CIkYW/kpR1JdwWDzXz593gaCizExhIlGUf914f53Iw=,tag:PoKwVmVextqWF4NU0Z2luQ==,type:str]
type: ENC[AES256_GCM,data:NO0530Ru,iv:Z5jbJn+gThgHxfT5PS1c7mmLpZLtNSxymegLYsa1l74=,tag:cFBtxdfvqLe2jqM09VzpVw==,type:str]
stringData:
    spicedb-preshared-key: ENC[AES256_GCM,data:M5AcV536c/8pamMAnMwswYpjmk1UaUrxCFYK00g4Sij9qlje3fvKDjpm9vxPRQai7M2zdrQzMTDw4adIa2y52g==,iv:q+GQ4WFPuCPbyJOsce8vkzlcMNdaxzYRKPbFxxbolYI=,tag:H3BT+hbigcgFeAo03rI0EQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEhMc3J5USBBMkxUWHAr
            QUMzSVR5ZVMzc1F4a3hTenRNcXRPYjdER0NNcE1ESWhaY0tuTwpaWWNpRjhDYUMv
            dHBYVlFFNWRqcTd2MzNTZzhkb0pzQlZiR01rRmNVRUFzCi0tLSBHMWdMcURLSGF4
            N1ZsQkpDY3dTb3RYUEtDQUYwWVBqdm5UZW1FQTROZG44Cj7I7h21fhhAq/RmZU2N
            y8laNxQiu2h6U5VxSypCImcvXfIHsW43ASLJYZBM+0uYJshXDxuUP7Urmwz5dtRe
            mlM=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qfn5svgndezuxfseqmq0f68sw8qex7scxrkgzjdjdm86hm6nxfmj5d8a97h
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBU2ZQMHZlYkpjek80ZG04
            YzNuWmlXSzI4eWNWRmQ0RTc2dDdlTlRucmk0CjFUTHExVy8wZ3ZSQlhZQ0s5MjlW
            RTFibnZHRDFhbXJuZXIvdW91OHNEVmcKLS0tIEJNa1F6UTFqbDdSNW00R1dYZHBU
            SDkzZ3JPZ2NGRmtmYTZtWVcvdWlzVDgKGm3G+ZUbHXdjyhtZikN7X2E/pFlRbZxm
            OTpMcFxiB35TBAv3ShZ9LEHh/BScqJ0Q+8La8l8P3CyyGtZ3g4bzhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t92fpnhk4s9apje356hfsadsh2c8prspmy6jshqfwn3dxyzr73sqpp4ac3
    lastmodified: "2026-08-20T15:39:01Z"
    mac: ENC[AES256_GCM,data:t08wGHbpMgeHbNfkI9Cv2R9gQcIDDB3sxv2J7/0YWe8S/hO+EcmSGImQ7w4CiDU65xunvrTsnImDIvQ9IeU+271cI7eCrnwKsYNwxL5SKuh/minW02D0VBUDDqBhDxklOES3mExnG1s8UZ/Jn4DSukt/xdPZZbKrim14Kt3rfsU=,iv:4vKV/wgj/yQXzxrNmEQQxfTZD9jDz2VMyMb7msWVxJw=,tag:EXFxCeLm3GW01ygPApXuTQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
