---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spicedb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spicedb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "spicedb.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
